import "./chartpanel";
import "./common/services/services";
import "./common/filters/filters";
import "./common/directives/all";
import "./user/userModule";
import "./org/orgModule";
import "./roles/all";
import "./department/all";
import "./project/all";
import "./overview/all";
import "./department/depviewCtrl";
import "./cvm/all";
import "./configure/all";
import "./logs/all";
import "./consumeStatistics/all";
import "./resourceprice/all";
import "./settings/all";
import "./system/all";
import "./topology/topologyCtrl";
import "./monitor/all";
import "./qcloud/all";
import "./menuManage/all";
import "./workflow/all";
import "./ticket/all";
import "./demotpl/demotplModule";
import physicalConductorModule from "./pvm/physicalConductor";
import physicalResourceModule from "./pvm/physicalResource";
import easyNetworkModule from "./easyReform";
import backupsModule from "./cvm/volumes";
import vmModule from "./cvm/instances";
import "./shortcuts/all";
import "./zrenderTopo";
import "./kubernetes/all";
import "./initSetting/all";
import "./commonModal";
import "./paas/all";
