let helpModule = angular.module("helpModule",[]);
helpModule.service("helpSrv",helpInit)
helpInit.$inject = ['$rootScope',"$window","$timeout","$http","$location","$translate"];
function helpInit(scope,$window,$timeout,$http,$location,$translate,alert){
    this.helpInformation = {
        //云主机列表
        "instances":{
            "route":"#/cvm/instances",
            "detailRoute":"/handbook/#/vm/concept",
            "data":[
                {
                    "title":"",
                    "describe":"云主机是云计算在基础设施应用上的重要组成部分，具有完整硬件、操作系统、网络功能，并且运行在一个完全隔离环境中的计算机系统。"
                }
            ]
        },
        //云主机组
        "affinity":{
            "route":"#/cvm/affinity",
            "detailRoute":"/handbook/#/vm/VMs",
            "data":[
                {
                    "title":"",
                    "describe":"当期望创建的云主机与某些特定的云主机分布在同一个物理节点上，以便这些云主机之间的通讯更快速方便时，可以把它们都放进同一个组；当期望创建的云主机与某些特定的云主机分布在不同的物理节点上，以便这些云主机之间实现一定的隔离，并且平衡各物理节点的资源使用率时，也可以把它们都放进同一个组。这些场景下所说的同一个组，即云主机组。"
                }
            ]
        },
        //虚拟网卡
        "ports":{
            "route":"#/cvm/ports",
            "detailRoute":"/handbook/#/vm/virtualNetworkAdapter",
            "data":[
                {
                    "title":"",
                    "describe":"云管平台支持关闭虚拟网卡的安全策略，允许用户手动在云主机的一个网卡上配置多个IP地址。为了防止手动分配的IP地址被其他用户分配到，设置虚拟网卡占用指定的IP地址。"
                },
                {
                    "title":"",
                    "describe":"虚拟网卡可以加载到云主机，一个主机最多可以加载26个网卡。"
                }
            ]
        },
        //镜像管理
        "images":{
            "route":"#/cvm/images",
            "detailRoute":"/handbook/#/vm/virtualNetworkAdapter",
            "data":[
                {
                    "title":"",
                    "describe":"镜像是一个包含操作系统及应用程序和服务的云主机模板。用户创建云主机时需要选定一个镜像，该镜像包含的操作系统及应用都会安装在云主机中。"
                },
                {
                    "title":"",
                    "describe":"云管平台安装部署完成后，需要将工具盘ISO中的cloudtools和其他操作系统镜像文件（raw、qcow2或者iso）上传到镜像库。其中raw和qcow2格式可以直接创建云主机，iso格式需要通过“制作镜像”功能才可制作成创建云主机可用的镜像。"
                }
            ]
        },
        //制作镜像
        "makeimages":{
            "route":"#/cvm/makeimages",
            "detailRoute":"/handbook/#/vm/createImage",
            "data":[
                {
                    "title":"",
                    "describe":"iso格式镜像文件上传到云管平台后，需要通过“制作镜像”功能才可制作成创建云主机可用的镜像。"
                }
            ]
        },
        //数据盘
        "volumesData":{
            "route":"#/cvm/volumes",
            "detailRoute":"/handbook/#/vm/cloudhardDisk",
            "data":[
                {
                    "title":"",
                    "describe":"云硬盘是一种采用网络存储架构，支持弹性扩展，并且由云主机进行管理和使用的虚拟块存储设备。"
                },
                {
                    "title":"",
                    "describe":"云硬盘类似于物理世界中的U盘或者移动硬盘,用户可以挂载到运行的云主机上，为主机提供持久化的存储。"
                },
                {
                    "title":"",
                    "describe":"云硬盘适用于文件系统、数据库或其他对容量、IO有需求的系统软件或应用。"
                }
            ]
        },
        //系统盘
        "volumesSystem":{
            "route":"#/cvm/volumes",
            "detailRoute":"/handbook/#/vm/cloudhardDisk",
            "data":[
                {
                    "title":"",
                    "describe":"云硬盘是一种采用网络存储架构，支持弹性扩展，并且由云主机进行管理和使用的虚拟块存储设备。"
                },
                {
                    "title":"",
                    "describe":"云硬盘类似于物理世界中的U盘或者移动硬盘,用户可以挂载到运行的云主机上，为主机提供持久化的存储。"
                },
                {
                    "title":"",
                    "describe":"云硬盘适用于文件系统、数据库或其他对容量、IO有需求的系统软件或应用。"
                }
            ]
        },
        //缓存盘
        "volumesCaching":{
            "route":"#/cvm/volumes",
            "detailRoute":"/handbook/#/vm/cloudhardDisk",
            "data":[
                {
                    "title":"",
                    "describe":"云硬盘是一种采用网络存储架构，支持弹性扩展，并且由云主机进行管理和使用的虚拟块存储设备。"
                },
                {
                    "title":"",
                    "describe":"云硬盘类似于物理世界中的U盘或者移动硬盘,用户可以挂载到运行的云主机上，为主机提供持久化的存储"
                },
                {
                    "title":"",
                    "describe":"云硬盘适用于文件系统、数据库或其他对容量、IO有需求的系统软件或应用。"
                }
            ]
        },
        //本地盘
        "volumesLocal":{
            "route":"#/cvm/volumes",
            "detailRoute":"/handbook/#/vm/cloudhardDisk",
            "data":[
                {
                    "title":"",
                    "describe":"云硬盘是一种采用网络存储架构，支持弹性扩展，并且由云主机进行管理和使用的虚拟块存储设备。"
                },
                {
                    "title":"",
                    "describe":"云硬盘类似于物理世界中的U盘或者移动硬盘,用户可以挂载到运行的云主机上，为主机提供持久化的存储"
                },
                {
                    "title":"",
                    "describe":"云硬盘适用于文件系统、数据库或其他对容量、IO有需求的系统软件或应用。"
                }
            ]
        },
        //数据盘快照
        "snapshotsData":{
            "route":"#/cvm/snapshots",
            "detailRoute":"/handbook/#/vm/snapshot",
            "data":[
                {
                    "title":"",
                    "describe":"云硬盘快照是某一时间点云硬盘状态的全貌，通过创建快照可以保留云硬盘的状态，以便后续能返回相同的状态。快照属于增量备份，这意味着仅保存设备上在最新快照之后有更改的数据，这将尽可能缩短创建快照所需的时间，且可以节省存储成本。"
                },
                {
                    "title":"",
                    "describe":"可以在云硬盘的任何状态下创建快照，但是，快照只能保存创建时间点时已经写入云硬盘的数据，若应用程序或其他进程在该时刻正在向该云硬盘写入数据，可能无法被保存下来。如果可以将所有文件写入暂停一段时间并创建快照，则该快照应该是完整的。如果无法暂停，则建议将该云硬盘从云主机中卸载、创建快照然后重新挂在到云主机上。"
                }
            ]
        },
        //系统盘快照
        "snapshotsSystem":{
            "route":"#/cvm/snapshots",
            "detailRoute":"/handbook/#/vm/snapshot",
            "data":[
                {
                    "title":"",
                    "describe":"云硬盘快照是某一时间点云硬盘状态的全貌，通过创建快照可以保留云硬盘的状态，以便后续能返回相同的状态。快照属于增量备份，这意味着仅保存设备上在最新快照之后有更改的数据，这将尽可能缩短创建快照所需的时间，且可以节省存储成本。"
                },
                {
                    "title":"",
                    "describe":"可以在云硬盘的任何状态下创建快照，但是，快照只能保存创建时间点时已经写入云硬盘的数据，若应用程序或其他进程在该时刻正在向该云硬盘写入数据，可能无法被保存下来。如果可以将所有文件写入暂停一段时间并创建快照，则该快照应该是完整的。如果无法暂停，则建议将该云硬盘从云主机中卸载、创建快照然后重新挂在到云主机上。"
                }
            ]
        },
        //备份
        //数据盘备份
        "dataBackups":{
            "route":"#/cvm/backups",
            "detailRoute":"/handbook/#/vm/backups",
            "data":[
                {
                    "title":"",
                    "describe":"备份是一种便捷高效的数据保护服务手段。数据盘的日常备份，可以定期备份重要业务数据，以应对误操作、攻击或病毒等导致的数据丢失风险。应用软件升级或业务数据迁移等重大操作前，可以创建一份或多份数据备份。一旦升级或迁移过程中出现任何问题，即可以通过数据备份及时将业务恢复到正常的系统数据状态。"
                }
            ]
        },
        //系统盘备份
        "systemBackups":{
            "route":"#/cvm/backups",
            "detailRoute":"/handbook/#/vm/backups",
            "data":[
                {
                    "title":"",
                    "describe":"备份是一种便捷高效的数据保护服务手段。数据盘的日常备份，可以定期备份重要业务数据，以应对误操作、攻击或病毒等导致的数据丢失风险。应用软件升级或业务数据迁移等重大操作前，可以创建一份或多份数据备份。一旦升级或迁移过程中出现任何问题，即可以通过数据备份及时将业务恢复到正常的系统数据状态。"
                }
            ]
        },
        //云硬盘Qos
        "volumesQoS":{
            "route":"#/cvm/volumesQoS",
            "detailRoute":"/handbook/#/vm/cloudhardDisk",
            "data":[
                {
                    "title":"",
                    "describe":"为防止部分云硬盘过多占用资源，影响整个存储效率，设置云硬盘的QoS来限制云硬盘读写吞吐量和操作数。"
                }
            ]
        },
        //网络拓扑
        "graffNet":{
            "route":"#/cvm/netTopo",
            "detailRoute":"/handbook/#/vm/router",
            "data":[
                {
                    "title":"",
                    "describe":"网络拓扑支持自动生成整个云管资源的网络连接关系，展示包括云主机、私有网络、虚拟路由器和云主机在内的层级连接关系。"
                }
            ]
        },
        //私有网络
        "networks":{
            "route":"#/cvm/networks",
            "detailRoute":"/handbook/#/vm/router",
            "data":[
                {
                    "title":"",
                    "describe":"私有网络是一个用户自定义的逻辑隔离网络空间，托管在私有网络内的是云主机、负载均衡资源。不同私有网络间完全逻辑隔离。用户可以自定义网段划分、IP地址和路由策略等，并通过防火墙和安全组等实现多层安全防护。"
                }
            ]
        },
        //路由器
        "routers":{
            "route":"#/cvm/routers",
            "detailRoute":"/handbook/#/vm/router",
            "data":[
                {
                    "title":"",
                    "describe":"路由器用于连接多个私有网络，使之互通。云主机可以通过路由器访问公网。"
                }
            ]
        },
        //外部网路
        "physicalnetworks":{
            "route":"#/cvm/physicalnetworks",
            "detailRoute":"/handbook/#/vm/externalNetwork",
            "data":[
                {
                    "title":"",
                    "describe":"外部网络是外部物理网络的映射，一般用于给虚拟路由器分配网关地址，或者给云主机分配公网IP地址。云主机使用外部网络对外提供业务能力。"
                }
            ]
        },
        //公网ip
        "floating_ips":{
            "route":"#/cvm/floating_ips",
            "detailRoute":"/handbook/#/vm/externalNetwork",
            "data":[
                {
                    "title":"",
                    "describe":"公网IP地址即互联网IP地址，若需要从外部网络访问云主机，则需要为云主机分配公网IP。先申请公网IP，然后将公网IP绑定到云主机或负载均衡等资源即可。（在私有云中，这里可以是公司内部业务的私网IP地址）"
                }
            ]
        },
        //负载均衡
        "loadbalancing":{
            "route":"#/cvm/loadbalancing",
            "detailRoute":"/handbook/#/vm/loadBalancing",
            "data":[
                {
                    "title":"",
                    "describe":"负载均衡可以将访问流量按照一定的均衡算法动态地分发到多台提供相同服务的云主机上，每台云主机都可以单独响应请求，从而提高业务的服务能力和可用性。同时，还可以随时通过添加或删减云主机来调整负载均衡的服务能力，而且这些操作不会影响业务的正常访问。目前支持HTTP/HTTPS/TCP三种监听模式。"
                }
            ]
        },
        //vpn
        "vpn":{
            "route":"#/cvm/vpn",
            "detailRoute":"/handbook/#/vm/IPSecVPN",
            "data":[
                {
                    "title":"",
                    "describe":"IPSec VPN指采用IPSec协议来实现远程接入的一种VPN技术，IPSec全称为Internet Protocol Security，是由Internet Engineering Task Force(IETF)定义的安全标准框架，用以提供公用和专用网络的端对端加密和验证服务。IPSec VPN用于连接两个私有云环境或者连接私有云和公有云环境，将两个不同私有网络环境整合成为一个统一的私有网络环境。"
                }
            ]
        },
        //防火墙
        "firewall":{
            "route":"#/cvm/firewall",
            "detailRoute":"/handbook/#/vm/securityGroup",
            "data":[
                {
                    "title":"",
                    "describe":"防火墙作用于路由器，保护路由器以及与路由器连通的整个内部网络免受外部网络的非法侵入。"
                }
            ]
        },
        //密钥对
        "keypairs":{
            "route":"#/cvm/keypairs",
            "detailRoute":"/handbook/#/vm/keyPair",
            "data":[
                {
                    "title":"",
                    "describe":"即常见的ssh-key的密钥对。可用于无密码无用户名登录Linux类型的云主机。仅支持Linux类型的云主机。在云管平台上生成密钥对并将私钥下载到用户本地，在创建云主机时选择对应的密钥对名称即可实现通过密钥方式登录云主机，从而保证云主机被访问的高度可控性。"
                }
            ]
        },
        //安全组
        "security_groups":{
            "route":"#/cvm/security_groups",
            "detailRoute":"/handbook/#/vm/securityGroup",
            "data":[
                {
                    "title":"",
                    "describe":"安全组是一个逻辑上的分组，可以实现相互信任的云主机之间的通信。可以将同一地域内具有相同网络安全隔离需求的云主机加到同一个安全组内，从而这些云主机使用相同的安全策略。"
                }
            ]
        },
        //扩展策略
        "scalpolicy":{
            "route":"#/cvm/scalpolicy",
            "detailRoute":"/handbook/#/vm/securityGroup",
            "data":[
                {
                    "title":"",
                    "describe":"根据用户的业务需求和策略，经济地自动调整弹性计算资源的管理服务。弹性扩展不仅适合业务量不断波动的应用程序，同时也适合业务量稳定的应用程序。"
                }
            ]
        },
        //集群管理
        "extension":{
            "route":"#/cvm/extension",
            "detailRoute":"/handbook/#/vm/securityGroup",
            "data":[
                {
                    "title":"",
                    "describe":"通过弹性扩展管理集群，在高峰期自动增加云主机，在业务回落时自动减少云主机，节省基础设施成本。"
                }
            ]
        },
        //回收站
        "recycle":{
            "route":"#/cvm/recycle",
            "detailRoute":"/handbook/#/vm/recycleBin",
            "data":[
                {
                    "title":"",
                    "describe":"回收站用于存放被删除的云主机，并在设置期限内提供云主机的恢复功能。当云平台管理员由于误操作删除云主机之后，可以在回收站中找到云主机并将云主机恢复回去。"
                }
            ]
        },
        //物理机
        "pvminstances":{
            "route":"#/pvm/pvminstances",
            "detailRoute":"/handbook/#/physic/physicalMachine",
            "data":[
                {
                    "title":"",
                    "describe":"物理机模块提供了物理资源管理中最基础的功能，即物理机从申请到删除的全生命周期维护。"
                }
            ]
        },
        //物理机镜像
        "pvmimages":{
            "route":"#/pvm/pvmimages",
            "detailRoute":"/handbook/#/physic/physicalMachine",
            "data":[
                {
                    "title":"",
                    "describe":"镜像功能模块用于为物理机提供镜像，通常包含了操作系统、应用程序及相关服务，通过此模块可以创建一台物理机为用户提供服务。"
                }
            ]
        },
        //物理机网络
        "pvmnetworks":{
            "route":"#/pvm/pvmnetworks",
            "detailRoute":"/handbook/#/physic/physicalMachine",
            "data":[
                {
                    "title":"",
                    "describe":"网络功能模块基于先进的SDN技术，为用户提供按需构建网络的功能。"
                }
            ]
        },
        //容器集群
        "k8sclusters":{
            "route":"#/k8s/clusters",
            "detailRoute":"/handbook/#/physic/containerCluster",
            "data":[
                {
                    "title":"帮助信息",
                    "describe":"容器集群使用帮助引导使用帮助引导使用使用帮助引导使助引导"
                }
            ]
        },
        //容器服务
        "k8sservices":{
            "route":"#/k8s/services",
            "detailRoute":"/handbook/#/physic/containerService",
            "data":[
                {
                    "title":"",
                    "describe":"容器服务基于原生Kubernetes 提供以容器为核心的、高度可扩展的高性能容器管理服务。容器服务完全兼容原生KubernetesAPI，为容器化的应用提供高效部署、资源调度、服务发现和动态伸缩等一系列完整功能，解决用户开发、测试及运维过程的环境一致性问题，提高了大规模容器集群管理的便捷性，帮助用户降低成本，提高效率。"
                }
            ]
        },
        //镜像服务
        "k8sprojects":{
            "route":"#/k8s/projects",
            "detailRoute":"/handbook/#/physic/imageService",
            "data":[
                {
                    "title":"帮助信息",
                    "describe":"镜像服务使用帮助引导使用帮助引导使用使用帮助引导使助引导"
                }
            ]
        },
        //告警事件
        "alarmevent":{
            "route":"#/monitor/alarmevent",
            "detailRoute":"/handbook/#/alarm/alarmSetting",
            "data":[
                {
                    "title":"",
                    "describe":"告警事件分为告警事件和历史告警。没有处理过的告警即为告警事件；已处理的告警为历史告警。"
                }
            ]
        },
        "wechatAlarmevent":{
            "route":"#/wechat/alarmEvent",
            "detailRoute":"/handbook/#/alarm/alarmSetting",
            "data":[
                {
                    "title":"",
                    "describe":"告警事件分为告警事件和历史告警。没有处理过的告警即为告警事件；已处理的告警为历史告警。"
                }
            ]
        },
        //历史告警事件
        "hisAlarmevent":{
            "route":"#/monitor/alarmevent",
            "detailRoute":"/handbook/#/alarm/alarmSetting",
            "data":[
                {
                    "title":"帮助信息",
                    "describe":"历史告警事件使用帮助引导使用帮助引导使用使用帮助引导使助引导"
                }
            ]
        },
        "wechatHisAlarmevent":{
            "route":"#/wechat/alarmSetting",
            "detailRoute":"/handbook/#/alarm/alarmSetting",
            "data":[
                {
                    "title":"帮助信息",
                    "describe":"历史告警事件使用帮助引导使用帮助引导使用使用帮助引导使助引导"
                }
            ]
        },
        //告警设置
        "alarmsetting":{
            "route":"#/monitor/alarmsetting",
            "detailRoute":"/handbook/#/alarm/alarmSetting",
            "data":[
                {
                    "title":"",
                    "describe":"系统已预置常用告警设置。如需创建告警设置，请确保已创建告警模板。"
                }
            ]
        },
        "wechatAlarmsetting":{
            "route":"#/wechat/alarmSetting",
            "detailRoute":"/handbook/#/alarm/alarmSetting",
            "data":[
                {
                    "title":"",
                    "describe":"系统已预置常用告警设置。如需创建告警设置，请确保已创建告警模板。"
                }
            ]
        },
        //告警模板
        "alarmtemplate":{
            "route":"#/monitor/alarmtemplate",
            "detailRoute":"/handbook/#/alarm/alarmTemplate",
            "data":[
                {
                    "title":"",
                    "describe":"用户可以根据实际需要对某个特定的监控指标设置自定义告警规则，同时也支持使用告警模板为多个资源或者服务创建告警。"
                }
            ]
        },
        "wechatAlarmtemplate":{
            "route":"#/wechat/alarmTemplate",
            "detailRoute":"/handbook/#/alarm/alarmTemplate",
            "data":[
                {
                    "title":"",
                    "describe":"用户可以根据实际需要对某个特定的监控指标设置自定义告警规则，同时也支持使用告警模板为多个资源或者服务创建告警。"
                }
            ]
        },
        //联系人组
        "contractgroup":{
            "route":"#/monitor/contractgroup",
            "detailRoute":"/handbook/#/alarm/contactGroup",
            "data":[
                {
                    "title":"",
                    "describe":"接收告警通知的邮箱或微信。"
                }
            ]
        },
        "wechatContractgroup":{
            "route":"#/wechat/alramContactGroup",
            "detailRoute":"/handbook/#/alarm/contactGroup",
            "data":[
                {
                    "title":"",
                    "describe":"接收告警通知的邮箱或微信。"
                }
            ]
        },

        //待处理工单
        "pendingTickets":{
            "route":"#/ticket/pendingTickets",
            "detailRoute":"/handbook/#/workOrder/managementOfWorkOrder",
            "data":[
                {
                    "title":"",
                    "describe":"在待处理工单页面对需要由当前登录用户审批的工单进行操作。"
                }
            ]
        },
        //我的申请
        "myApply":{
            "route":"#/ticket/myApply",
            "detailRoute":"/handbook/#/workOrder/managementOfWorkOrder",
            "data":[
                {
                    "title":"",
                    "describe":"在我的申请页面，可以查看当前登录用户提交的工单申请"
                }
            ]
        },
        //我的审批
        "allTickets":{
            "route":"#/ticket/allTickets",
            "detailRoute":"/handbook/#/workOrder/managementOfWorkOrder",
            "data":[
                {
                    "title":"",
                    "describe":"在我的审批页面，可以查看当前登录用户已经审批的工单。"
                }
            ]
        },
        //工单报表
        "ticketReports":{
            "route":"#/ticket/ticketReports",
            "detailRoute":"/handbook/#/workOrder/managementOfWorkOrder",
            "data":[
                {
                    "title":"",
                    "describe":"按照不同的过滤条件，查看工单信息。"
                }
            ]
        },
        //操作日志
        "operatelogs":{
            "route":"#/logs/operatelogs",
            "detailRoute":"/handbook/#/log/logManagement",
            "data":[
                {
                    "title":"",
                    "describe":"记录了云管系统各个功能模块的业务变化、业务状态变化"
                }
            ]
        },
        //部门管理
        "department":{
            "route":"#/permit/department",
            "detailRoute":"/handbook/#/identity/identityManagement",
            "data":[
                {
                    "title":"",
                    "describe":"每个部门有自己独立的资源池，部门管理员可自主管理和部署名下的资源。部门之间的资源是相互隔离的。此页面可以创建和管理云平台中的部门，并管理每个部门的配额。"
                }
            ]
        },
        //项目管理
        "project":{
            "route":"#/permit/project",
            "detailRoute":"/handbook/#/identity/identityManagement",
            "data":[
                {
                    "title":"",
                    "describe":"项目是云平台中人或服务所拥有的资源集合，一个项目可以包括多个用户，每个用户会根据权限来使用项目中的资源。这里可以对项目进行配额管理，但是项目的配额不能高于其所属的部门配额。"
                }
            ]
        },
        //用户管理
        "user":{
            "route":"#/permit/user",
            "detailRoute":"/handbook/#/identity/identityManagement",
            "data":[
                {
                    "title":"",
                    "describe":"通过为用户设定角色，赋予用户一定的权限，以满足不同用户对系统的访问控制需求。用户角色分为部门管理员、项目管理员和普通用户。部门管理员可以管理本部门的所有项目管理员和普通用户，项目管理员可以管理本项目内的所有普通用户。"
                }
            ]
        },
        //角色管理
        "role":{
            "route":"#/permit/role",
            "detailRoute":"/handbook/#/identity/identityManagement",
            "data":[
                {
                    "title":"",
                    "describe":"支持基于部门、项目及项目成员划分角色（部门管理员、项目管理员和普通用户），并基于角色分配云管平台的功能权限。"
                }
            ]
        },
        //主机集合
        "aggregates":{
            "route":"#/system/aggregates",
            "detailRoute":"/handbook/#/maintenance/hostSet",
            "data":[
                {
                    "title":"",
                    "describe":"主机集合即具有共同属性的物理机组成的一个逻辑的小集群。它需要和可用域配合使用；可用域更多表现为地理概念，如当一个集群跨域两个机房时，则每个机房作为一个可用域。而主机集合将把可用域中具有相同属性或者相同用途的物理主机归类到同一主机集合中。让用户在创建云主机时可以自动调度到想要的物理主机上。"
                }
            ]
        },
        //数据中心管理
        "datacluster":{
            "route":"#/system/datacluster",
            "detailRoute":"/handbook/#/maintenance/dataCenterManagement",
            "data":[
                {
                    "title":"",
                    "describe":"当云管平台采用公共云管部署模式时，支持多数据中心统一管理和部署。"
                }
            ]
        },
        //节点管理
        "node":{
            "route":"#/configure/node",
            "detailRoute":"/handbook/#/maintenance/nodeManagement",
            "data":[
                {
                    "title":"",
                    "describe":"通过对节点进行管理，实现集群、高可用等功能特性。请注意新增节点如果超过30分钟还没初始化完成，请排查节点是否有故障。"
                }
            ]
        },
        //纳管物理机
        "physicalConductor":{
            "route":"#/system/physicalConductor",
            "detailRoute":"/handbook/#/maintenance/nanofilmPhysicalMachine",
            "data":[
                {
                    "title":"",
                    "describe":"纳管物理机分为闲置物理机和运行中的物理机两类。将处于运行状态的物理机纳入管理，监控物理机状态；将闲置的物理机组成资源池，提供租用服务。对已纳管的物理机进行开机、关机、重启、控制台、查看硬件配置信息等操作。"
                }
            ]
        },
        //资源池物理机
        "physicalConductor_res":{
            "route":"#/system/physicalConductor",
            "detailRoute":"/handbook/#/maintenance/resourcePoolPhysicalMachine",
            "data":[
                {
                    "title":"",
                    "describe":"纳管物理机分为闲置物理机和运行中的物理机两类。将处于运行状态的物理机纳入管理，监控物理机状态；将闲置的物理机组成资源池，提供租用服务。对已纳管的物理机进行开机、关机、重启、控制台、查看硬件配置信息等操作。"
                }
            ]
        },
        //存储管理
        "storageManagement":{
            "route":"#/system/storageManagement",
            "detailRoute":"/handbook/#/maintenance/storageManagement",
            "data":[
                {
                    "title":"",
                    "describe":"配置云主机备份资源池或云主机存储资源池对接的外部存储设备信息。"
                }
            ]
        },
        //镜像库管理
        "imageManagement":{
            "route":"#/system/imageManagement",
            "detailRoute":"/handbook/#/maintenance/imagesManagement",
            "data":[
                {
                    "title":"",
                    "describe":"镜像库管理使用说明"
                }
            ]
        },
        //计划任务
        "regularSnap":{
            "route":"#/system/regularSnap",
            "detailRoute":"/handbook/#/maintenance/plannedTask",
            "data":[
                {
                    "title":"",
                    "describe":"创建计划任务，按照制定的定时任务执行策略定期执行备份、快照任务。"
                }
            ]
        },
        //透传设备
        "transmissionMag":{
            "route":"#/system/transmissionMag",
            "detailRoute":"/handbook/#/maintenance/transmissionEquipmentManagement",
            "data":[
                {
                    "title":"",
                    "describe":"将挂载在物理机上的U盘或硬盘等设备透传给云主机，云主机可以使用该透传设备。"
                }
            ]
        },
        //规格
        //云主机
        "flavorsinstance":{
            "route":"#/system/flavors",
            "detailRoute":"/handbook/#/operate/specifications",
            "data":[
                {
                    "title":"",
                    "describe":"云主机规格，即表示创建云主机所需要的相关配置，包括云主机的CPU个数、内存，以及相关的其他一些信息"
                }
            ]
        },
        //物理机
        "flavorsphysical":{
            "route":"#/system/flavors",
            "detailRoute":"/handbook/#/operate/specifications",
            "data":[
                {
                    "title":"",
                    "describe":"物理机规格即创建物理机所需要的相关配置，包括CPU个数、内存，以及相关的其他一些信息。"
                }
            ]
        },
        //流程管理
        //工作流程
        "flowManage":{
            "route":"#/system/flowManage",
            "detailRoute":"/handbook/#/operate/processManagement",
            "data":[
                {
                    "title":"",
                    "describe":"工作流管理用于设置工单审批全流程所涉及到的工单流转、各环节审批人及适用范围等。用户只有在此新建工单的审批流程后，才能在\"工单申请\"中看到相应的申请入口。"
                }
            ]
        },
        //自定义流程
        "flowManageCustom":{
            "route":"#/system/flowManage",
            "detailRoute":"/handbook/#/operate/processManagement",
            "data":[
                 {
                    "title":"",
                    "describe":"自定义流程用于定义流程级数及流程图等基本信息。"
                }
                
            ]
        },
        //软件授权
        "license":{
            "route":"#/system/license",
            "detailRoute":"/handbook/#/system/softwareAuthorization",
            "data":[
                {
                    "title":"",
                    "describe":"单击\"获取机器码\"，将机器码按照要求发送给厂商，待收到厂商关于激活文件的回复邮件后，点击\"导入激活文件\"将激活文件导入即可。"
                }
            ]
        },
        //功能管理
        "plugin":{
            "route":"#/system/plugin",
            "detailRoute":"/handbook/#/system/functionManagement",
            "data":[
                {
                    "title":"",
                    "describe":"功能管理用于安装云平台扩展功能模块。注：只可安装license授权范围内的功能模块；若在添加中没有找到您要安装的模块，请检查license授权范围是否涵盖该模块。"
                }
            ]
        },
        //云平台升级
        "grade":{
            "route":"#/system/grade",
            "detailRoute":"/handbook/#/system/cloudPlatformUpgrade",
            "data":[
                {
                    "title":"",
                    "describe":"请通过下面SFTP地址上传软件升级包，如需Windows SFTP客户端请点击下载"
                }
            ]
        },
        //安全设置
        "accesspolicy":{
            "route":"#/system/accesspolicy",
            "detailRoute":"/handbook/#/system/securitySet",
            "data":[
                {
                    "title":"",
                    "describe":"通过设置访问的黑白名单，来过滤云管平台的访问权限，以保障云管平台的使用安全。"
                }
            ]
        },
        //云系统服务
        "openstackService":{
            "route":"#/monitor/openstackService",
            "detailRoute":"/handbook/#/alarm/alarmSetting",
            "data":[
                {
                    "title":"",
                    "describe":"监控集群当前计算、存储、网络各服务的使用情况和运行状态。"
                }
            ]
        },
        //ceph管理
        "cephManage":{
            "route":"#/system/cephView",
            "detailRoute":"/handbook/#/maintenance/CephManagement",
            "data":[
                {
                    "title":"",
                    "describe":"云管平台对当前Ceph存储中各服务器的硬盘使用情况、硬盘更换、硬盘使用率等进行监控，并通过图形化或者列表式页面展示。"
                }
            ]
        },
        //关系型数据库
        "databasetdsql":{
            "route":"#/database/relationalTdsql",
            "detailRoute":"",
            "data":[
                {
                    "title":"",
                    "describe":"关系型数据库咋样"
                }
            ]
        },
        //系统巡检
        "inspection":{
            "route":"#/system/systeminspection",
            "detailRoute":"/handbook/#/maintenance/systemInspection",
            "data":[
                {
                    "title":"",
                    "describe":"系统巡检支持对整个云管平台进行全面的检查，以便及时发现问题。"
                },
                {
                    "title":"",
                    "describe":"在巡检过程中，会有如下操作:"
                },
                {
                    "title":"",
                    "describe":"1、系统在Web界面上，通过自动创建/删除云主机、镜像、密钥对、云硬盘、用户等操作，来验证相关功能是否正常，其中自动创建/删除期间，Web界面会弹出相关功能验证的提示框。"
                },
                {
                    "title":"",
                    "describe":"2、系统通过对底层命令的调用，进行各个节点的CPU、内存分区等使用情况的巡检。"
                },
                {
                    "title":"",
                    "describe":"3、系统采用超融合ceph时，会对存储的状态和使用情况进行巡检。"
                },
                {
                    "title":"",
                    "describe":"4、系统通过调用OpenStack API接口，对各个服务状态进行巡检"
                }
            ]
        }

    }
}

export default helpModule.name;
